services:
  backend:
    build:
      context: ./backend
    container_name: document-summarizer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
  
  frontend:
    build:
      context: ./frontend
    container_name: document-summarizer-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend